# Site settings
title: Srikrishnan Research Group
email: vs498@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the website for the Srikrishnan Research Group at Cornell BEE. We study the impact of dynamic environmental hazards, particularly those intensified by climate change, on infrastructure performance and management. We are interested in a broad range of applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
github:  srikrishnan-lab
office: 318 Riley-Robb Hall
department: Biological & Environmental Engineering
city: Ithaca, NY
zip: 14853-5701

# Build settings
markdown: kramdown

# Other options
permalink: /:year/:month/:title/
excerpt_separator: "<!--more-->"

# logos and images
logo_group: /assets/img/logos/sea_level_rise_banner.png
logo_cornell: /assets/img/logos/cornell-reduced-red.svg

# settings for deploy rake task
safe: False
lsi: False
username: srikrishnan-lab
repo: srikrishnan-lab.github.io
branch: master
destination: _site
production_url: https://srikrishnan-lab.github.io
source_url: https://github.com/srikrishnan-lab/srikrishnan-lab.github.io

#plugins_dir: "_plugins"
#plugins:
#  - jekyll-scholar

exclude:
  - "scripts"
  - "README.md"
  - ".DS_Store"
  - "assets/less/"
  - "vendor"
  - "pages/publications.html"
  - "_layouts/bib.html"

scholar:
  style: american-geophysical-union
  source: ./_bibliography
  bibliography: library.bib
  bibliography_template: bib
  sort_by: date,year,month
  order: descending
  bibliography_list_tag: div
  bibliography_item_tag: div
